### ISSUE TITLE
netlify link: react-conf link is redirecting to droidjam

### ISSUE THREAD

**Issue by rajaishwary** [ananyaneogi/dev-conferences-india#4]
Deploy updated version

**Comment by ananyaneogi** [comment]
@rajaishwary I don't understand. The React India conference link goes to the correct website as I checked. Can you elaborate more?

**Comment by rajaishwary** [comment]
basically, saw this on macOs only. 
couldn't replicate on other machine. I tried deploying current branch on netlify. It was working as expected.
but current live link is buggy. Checkout below link:
https://drive.google.com/folderview?id=11ugjpOpipr9FAPiwRJA25FNQQyc0mBL1

filter + date sort could be an issue.

**Comment by ananyaneogi** [comment]
@rajaishwary Thanks for letting me know. I've fixed the issue for now. 
Will check what caused the issue in the first place!
